name: Update README with Tistory Blog

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch blog feed and update README
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://api.rss2json.com/v1/api.json?rss_url=https://paicearea.tistory.com/rss"
